
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

from shared_conf import *

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'
